name: dosify_flutter
description: "Comprehensive medication management application with auto-reconstitution calculations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.4
  
  # Navigation
  go_router: ^12.1.3
  
  # Database - SQLite
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Utility packages
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # UI Components
  flutter_staggered_animations: ^1.1.1
  table_calendar: ^3.0.9
  
  # Material Design 3 & 2025 UI Enhancements
  lottie: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  dynamic_color: ^1.7.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0
  
  # Google Fonts (Serif fonts for 2025 trends)
  google_fonts: ^6.2.1
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Math utilities
  collection: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
